## Time
The leading constraint for this project is time to completion. Leading decisions will need to be made along the progress of this project with respect to the time that can be given to certain areas of the project. Depending on speed of progress, certain aspects of the final product may be limited in function or scope. As an example, it would be more time efficient to simply control the microcontroller with a wired controller rather than developing a radio controller. Since this is a one-person team, certain aspects of the physical design such as 3D printing of physical components or creating of electrical circuits could be completed with help from other, possibly more knowledgeable, colleagues who are willing to help and will thusly be credited in the final presentation. This would allow more time to be allotted to application and microcontroller code development.

## Economic Costs
Another leading constraint will be the cost of components. As this project serves as a prototype or proof of concept for a physical product, most components will most likely be on the cheaper side of what is available. This would mean that the physical aspects may not be as nice as envisioned or compelling enough to make the device completely useful or convenient. Such aspects that could be affected include quality of attachment hardware, speed and/or torque of motor and battery life.

## Professional/Technical
While this project does not require super specialized technical expertise, it does cross in certain areas of which I am only slightly familiar in. Mobile App development, electrical engineering, and 3D printing are some aspects that I am not extremely well versed in and will limit the complexity of this project in those regions. Since I am not an expert, I do plan to reach out to colleagues in those fields who can offer support in these areas.

## Cultural

As a project focused on creation of a physical product, the amount of use the target audience would get out of the product would impact the final design. While this aspect might affect the style or design of the product, there will not be a significant focus placed on this aspect for the project. Physical appearance, battery life, name, color, finish materials, speed and acceleration are among a few things that would be fine-tuned to user-based use cases. More in depth review and research into the target audience, use cases, and current competitors on the market would be required to place a higher emphasis on this product being successful. As this is a SR design project, such research will not be the focus.
